project: redmine
version: 0.42.3

repositories:
  - name: redmine
    url: https://techpipe-io.github.io/redmine-helm-chart

releases:
  - name: redmine
    namespace: redmine
    create_namespace: true
    chart:
      name: ./redmine
    values:
      - src: ./redmine/values.override.yaml
        render: false
        strict: true
    wait: true
    wait_for_jobs: true
    timeout: 15m
    max_history: 3
    atomic: false
    cleanup_on_fail: false
