image:
  tag: 6.1.3-trixie

replicaCount: 1

migrations:
  mode: startup
  plugins: false

secretKeyBase:
  existingSecret: redmine-runtime
  key: secret-key-base

persistence:
  files:
    enabled: true
    create: false
    existingClaim: redmine-files
  sqlite:
    enabled: true
    create: false
    existingClaim: redmine-sqlite
  config:
    enabled: true
    create: false
    existingClaim: redmine-config
    prepareConfigurationFile: true
    mounts:
      - mountPath: /usr/src/redmine/config/configuration.yml
        subPath: configuration.yml
        readOnly: true
  plugins:
    enabled: false
    create: false
    existingClaim: redmine-plugins
  public:
    enabled: false
    create: false
    existingClaim: redmine-public
